// Generated by gencpp from file blink_led/NotRequest.msg
// DO NOT EDIT!


#ifndef BLINK_LED_MESSAGE_NOTREQUEST_H
#define BLINK_LED_MESSAGE_NOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blink_led
{
template <class ContainerAllocator>
struct NotRequest_
{
  typedef NotRequest_<ContainerAllocator> Type;

  NotRequest_()
    : a(0)  {
    }
  NotRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;




  typedef boost::shared_ptr< ::blink_led::NotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blink_led::NotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NotRequest_

typedef ::blink_led::NotRequest_<std::allocator<void> > NotRequest;

typedef boost::shared_ptr< ::blink_led::NotRequest > NotRequestPtr;
typedef boost::shared_ptr< ::blink_led::NotRequest const> NotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blink_led::NotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blink_led::NotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blink_led

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'blink_led': ['/home/ayushgarg/catkin_ws/src/blink_led/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blink_led::NotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blink_led::NotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blink_led::NotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blink_led::NotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blink_led::NotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blink_led::NotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blink_led::NotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const ::blink_led::NotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x019706110004b728ULL;
  static const uint64_t static_value2 = 0xd56d8baaa8e32797ULL;
};

template<class ContainerAllocator>
struct DataType< ::blink_led::NotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blink_led/NotRequest";
  }

  static const char* value(const ::blink_led::NotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blink_led::NotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n\
";
  }

  static const char* value(const ::blink_led::NotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blink_led::NotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct NotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blink_led::NotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blink_led::NotRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLINK_LED_MESSAGE_NOTREQUEST_H
