// Generated by gencpp from file blink_led/NotResponse.msg
// DO NOT EDIT!


#ifndef BLINK_LED_MESSAGE_NOTRESPONSE_H
#define BLINK_LED_MESSAGE_NOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blink_led
{
template <class ContainerAllocator>
struct NotResponse_
{
  typedef NotResponse_<ContainerAllocator> Type;

  NotResponse_()
    : task()  {
    }
  NotResponse_(const ContainerAllocator& _alloc)
    : task(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_type;
  _task_type task;




  typedef boost::shared_ptr< ::blink_led::NotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blink_led::NotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NotResponse_

typedef ::blink_led::NotResponse_<std::allocator<void> > NotResponse;

typedef boost::shared_ptr< ::blink_led::NotResponse > NotResponsePtr;
typedef boost::shared_ptr< ::blink_led::NotResponse const> NotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blink_led::NotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blink_led::NotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blink_led

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'blink_led': ['/home/ayushgarg/catkin_ws/src/blink_led/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blink_led::NotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blink_led::NotResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blink_led::NotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blink_led::NotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blink_led::NotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blink_led::NotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blink_led::NotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ece8f504419f7ca4d91b277e47ff617";
  }

  static const char* value(const ::blink_led::NotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ece8f504419f7caULL;
  static const uint64_t static_value2 = 0x4d91b277e47ff617ULL;
};

template<class ContainerAllocator>
struct DataType< ::blink_led::NotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blink_led/NotResponse";
  }

  static const char* value(const ::blink_led::NotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blink_led::NotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task\n\
\n\
";
  }

  static const char* value(const ::blink_led::NotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blink_led::NotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct NotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blink_led::NotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blink_led::NotResponse_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLINK_LED_MESSAGE_NOTRESPONSE_H
